[package]
name = "redis_derive"
version = "0.1.0"
edition = "2024"
description = "Derive Redis JSON serialization and deserialization"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = { version = "1" }
syn = { version = "2", features = ["derive"] }

[dev-dependencies]
redis = { version = "0.32.7" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
